
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

#include "naloga2.h"

int __main__() {
    A* a1 = malloc(sizeof(A));
    a1->p = -343;
    B* b1 = malloc(sizeof(B));
    b1->q = "hcQuvlPd";
    C* c1 = malloc(sizeof(C));
    c1->r = false;
    A* a2 = malloc(sizeof(A));
    a2->p = 12;
    B* b2 = malloc(sizeof(B));
    b2->q = "z94pStuCf";
    C* c2 = malloc(sizeof(C));
    c2->r = true;
    A* a3 = malloc(sizeof(A));
    a3->p = 544;
    B* b3 = malloc(sizeof(B));
    b3->q = "IilyMpH_Lb";
    C* c3 = malloc(sizeof(C));
    c3->r = false;
    c3->a = NULL;
    B* b4 = malloc(sizeof(B));
    b4->q = "VoCWP";
    C* c4 = malloc(sizeof(C));
    c4->r = true;
    c4->a = NULL;
    c4->b = NULL;
    b4->c = c4;
    c3->b = b4;
    b3->c = c3;
    a3->b = b3;
    c2->a = a3;
    B* b5 = malloc(sizeof(B));
    b5->q = "orYvBjCmDN";
    C* c5 = malloc(sizeof(C));
    c5->r = true;
    c5->a = NULL;
    B* b6 = malloc(sizeof(B));
    b6->q = "QH";
    C* c6 = malloc(sizeof(C));
    c6->r = false;
    A* a4 = malloc(sizeof(A));
    a4->p = 396;
    B* b7 = malloc(sizeof(B));
    b7->q = "7apQ";
    C* c7 = malloc(sizeof(C));
    c7->r = true;
    A* a5 = malloc(sizeof(A));
    a5->p = -765;
    B* b8 = malloc(sizeof(B));
    b8->q = "IiJ1t3z";
    C* c8 = malloc(sizeof(C));
    c8->r = false;
    A* a6 = malloc(sizeof(A));
    a6->p = 810;
    B* b9 = malloc(sizeof(B));
    b9->q = "PdVbc3w";
    b9->c = NULL;
    a6->b = b9;
    c8->a = a6;
    c8->b = NULL;
    b8->c = c8;
    a5->b = b8;
    c7->a = a5;
    B* b10 = malloc(sizeof(B));
    b10->q = "oxizpn0a";
    b10->c = NULL;
    c7->b = b10;
    b7->c = c7;
    a4->b = b7;
    c6->a = a4;
    B* b11 = malloc(sizeof(B));
    b11->q = "gmNIF2bo4X";
    C* c9 = malloc(sizeof(C));
    c9->r = true;
    c9->a = NULL;
    B* b12 = malloc(sizeof(B));
    b12->q = "9dXB";
    C* c10 = malloc(sizeof(C));
    c10->r = false;
    c10->a = NULL;
    c10->b = NULL;
    b12->c = c10;
    c9->b = b12;
    b11->c = c9;
    c6->b = b11;
    b6->c = c6;
    c5->b = b6;
    b5->c = c5;
    c2->b = b5;
    b2->c = c2;
    a2->b = b2;
    c1->a = a2;
    B* b13 = malloc(sizeof(B));
    b13->q = "9HakKAP";
    C* c11 = malloc(sizeof(C));
    c11->r = true;
    c11->a = NULL;
    c11->b = NULL;
    b13->c = c11;
    c1->b = b13;
    b1->c = c1;
    a1->b = b1;

    char* cilj = malloc(10010 * sizeof(char));
    int stZnakov = izpisiA(a1, cilj);
    printf("%s\n", cilj);
    printf("%d\n", stZnakov);
    free(cilj);

    free(a1);
    free(b1);
    free(c1);
    free(a2);
    free(b2);
    free(c2);
    free(a3);
    free(b3);
    free(c3);
    free(b4);
    free(c4);
    free(b5);
    free(c5);
    free(b6);
    free(c6);
    free(a4);
    free(b7);
    free(c7);
    free(a5);
    free(b8);
    free(c8);
    free(a6);
    free(b9);
    free(b10);
    free(b11);
    free(c9);
    free(b12);
    free(c10);
    free(b13);
    free(c11);

    exit(0);
    return 0;
}
